<?php
/*  Class Generated by Brendon Irwin's Class Generator

	Class: Formsavejson

	entryID, i
	data, lt

*/

	class Formsavejson{
		private $id;
		private $connection;
		private $errors;
		private $errorCount;
		private $entryID;
		private $data;


		/*Constructor*/
		function __construct($databaseConnection=null){
			$this->connection = $databaseConnection;
		}

		/*Getters and Setters*/
		function getId(){
			return $this->id;
		}

		function setId($id){
			$this->id = $id;
		}

		function getConnection(){
			return $this->connection;
		}

		function setConnection($connection){
			$this->connection = $connection;
		}

		function getErrors(){
			return $this->errors;
		}

		function setErrors($errors){
			$this->errors = $errors;
		}

		function getErrorCount(){
			return $this->errorCount;
		}

		function setErrorCount($errorCount){
			$this->errorCount = $errorCount;
		}

		function getEntryID(){
			return $this->entryID;
		}

		function setEntryID($entryID){
			$this->entryID = $entryID;
		}

		function getData(){
			return $this->data;
		}

		function setData($data){
			$this->data = $data;
		}

		/*Special Functions*/
		function load($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("SELECT * FROM `formsavejson` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						$formsavejson = $query->fetchObject("formsavejson");
					}
					if( is_object( $formsavejson ) ){
						$formsavejson->setConnection( $this->connection );
					}
					return $formsavejson;
				}
			}
		}

		function getFromPost(){
			$this->setEntryID( (isset($_POST["entryID"])) ? $_POST["entryID"] : $this->getEntryID() );
			$this->setData( (isset($_POST["data"])) ? $_POST["data"] : $this->getData() );
		}

		function getFromRequest(){
			$this->setEntryID( (isset($_REQUEST["entryID"])) ? $_REQUEST["entryID"] : $this->getEntryID() );
			$this->setData( (isset($_REQUEST["data"])) ? $_REQUEST["data"] : $this->getData() );
		}

		function getFromArray($arr){
			$this->setEntryID( (isset($arr["entryID"])) ? $arr["entryID"] : $this->getEntryID() );
			$this->setData( (isset($arr["data"])) ? $arr["data"] : $this->getData() );
		}

		function compareTo($formsavejson){
			$log = array();
			if($this->getId() != $formsavejson->getId() ){
				$log["Id"] = "modified";
			}else{
				$log["Id"] = "un-modified";
			}
			if($this->getConnection() != $formsavejson->getConnection() ){
				$log["Connection"] = "modified";
			}else{
				$log["Connection"] = "un-modified";
			}
			if($this->getErrors() != $formsavejson->getErrors() ){
				$log["Errors"] = "modified";
			}else{
				$log["Errors"] = "un-modified";
			}
			if($this->getErrorCount() != $formsavejson->getErrorCount() ){
				$log["ErrorCount"] = "modified";
			}else{
				$log["ErrorCount"] = "un-modified";
			}
			if($this->getEntryID() != $formsavejson->getEntryID() ){
				$log["EntryID"] = "modified";
			}else{
				$log["EntryID"] = "un-modified";
			}
			if($this->getData() != $formsavejson->getData() ){
				$log["Data"] = "modified";
			}else{
				$log["Data"] = "un-modified";
			}
		return $log;
		}

		function save(){
			$id = $this->getId();
			$entryID = $this->getEntryID();
			$data = $this->getData();
			if( $this->connection ){
				if( $id != "" ){
					/*Perform Update Operation*/
					$query = $this->connection->prepare("UPDATE  `formsavejson` SET `entryID` = :entryID ,`data` = :data WHERE `id` = :id");
					$query->bindParam('entryID', $entryID);
					$query->bindParam('data', $data);
					$query->bindParam('id', $id);
					if( $query->execute() ){
						return $id;
					}else{
						return -1;
					}

				}else{
					/*Perform Insert Operation*/
					$query = $this->connection->prepare("INSERT INTO `formsavejson` (`id`,`entryID`,`data`) VALUES (NULL,:entryID,:data);");
					$query->bindParam(':entryID', $entryID);
					$query->bindParam(':data', $data);

					if( $query->execute() ){
						$this->setId( $this->connection->lastInsertId() );
						return $this->getId();
					}else{
						return -1;
					}	
				}
			}
		}


		function delete($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("DELETE FROM `formsavejson` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						return 1;
					}else{
						return 0;
					}
				}
			}
		}

		function getById($id){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formsavejson` WHERE `id` = :id LIMIT 1");
				$query->bindParam(':id', $id);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("formsavejson") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByEntryID($entryID){
			if( $this->connection ){
				if( $entryID == null && $this->getEntryID() != ""){
					$entryID = $this->getEntryID();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formsavejson` WHERE `entryID` = :entryID LIMIT 1");
				$query->bindParam(':entryID', $entryID);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("formsavejson") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByData($data){
			if( $this->connection ){
				if( $data == null && $this->getData() != ""){
					$data = $this->getData();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formsavejson` WHERE `data` = :data LIMIT 1");
				$query->bindParam(':data', $data);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("formsavejson") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}


		function getListById($id=null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formsavejson` WHERE `id` = :id");
				$query->bindParam(':id', $id);

				if( $query->execute() ){
					while( $result = $query->fetchObject("formsavejson") ){
						$formsavejsons[] = $result;
					}
					if( is_array( $formsavejsons ) ){
						return $formsavejsons;
					}else{
						return array();
					}

				}
			}
		}

		function getListByEntryID($entryID=null){
			if( $this->connection ){
				if( $entryID == null && $this->getEntryID() != ""){
					$entryID = $this->getEntryID();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formsavejson` WHERE `entryID` = :entryID");
				$query->bindParam(':entryID', $entryID);

				if( $query->execute() ){
					while( $result = $query->fetchObject("formsavejson") ){
						$formsavejsons[] = $result;
					}
					if( is_array( $formsavejsons ) ){
						return $formsavejsons;
					}else{
						return array();
					}

				}
			}
		}

		function getListByData($data=null){
			if( $this->connection ){
				if( $data == null && $this->getData() != ""){
					$data = $this->getData();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formsavejson` WHERE `data` = :data");
				$query->bindParam(':data', $data);

				if( $query->execute() ){
					while( $result = $query->fetchObject("formsavejson") ){
						$formsavejsons[] = $result;
					}
					if( is_array( $formsavejsons ) ){
						return $formsavejsons;
					}else{
						return array();
					}

				}
			}
		}

		/*Return parameter (object) as Array*/
		function toArray ($obj=null) {
			if (is_object($obj)) $obj = (array)$obj;
			if (is_array($obj)) {
				$new = array();
				foreach ($obj as $key => $val) {
					$class = get_class($this);
					$k = $key;
					$fkey = trim( str_replace( $class,"",$k));
					if( $fkey == "connection" || $fkey == "errors" || $fkey == "errorCount" ){
						//dont add
					}else{
						$new[$fkey] = $this->toArray($val);
					}
				}
			} else {
				$new = $obj;
			}
			return $new;
		}

		/*Return object as Array*/
		function asArray(){
			$array = $this->toArray( $this );
			return $array;
		}

		/*Return object as JSON String*/
		function asJSON(){
			return json_encode($this->asArray());
		}

		/*Return clone of Object*/
		function getClone(){
			return clone($this);
		}


		/*Echo array as CSV file*/
		function arrayToCSVFile($array, $filename="formsavejson.csv", $delimiter=",", $showHeader=true){
			ob_clean();
			if( !is_array($array) ){
				$array = $this->asArray();
			}
			if( !is_array($showHeader) && $showHeader == true){
				$header=array();
				foreach( $array[0] as $key => $value){
					$header[] = strtoupper($key);
				}
				array_unshift($array, $header);
			}
			if( is_array($showHeader) ){
				array_unshift($array, $showHeader);
			}
			header('Content-Type: application/csv; charset=UTF-8');
			header('Content-Disposition: attachement; filename="'.$filename.'";');
			$f = fopen('php://output', 'w');
			foreach ($array as $line) {
				fputcsv($f, $line, $delimiter);
			}
			exit;
		}


		/*getObjectsLikeThis - returns array*/
		function getObjectsLikeThis($asArray=true){
			if( $this->connection ){
				$buildQuery="SELECT * FROM `formsavejson` WHERE ";
				$numParams = 0;
				$values = array();
				foreach ($this as $key => $value) {
					if( $value != "" && $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
						$buildQuery.="`".$key."` = :value_".$numParams." AND ";
						$numParams++;
						$values[] = $value;
					}
				}
				if( $numParams > 0 ){
					//remove last AND
					$buildQuery = substr( $buildQuery , 0, (strlen($buildQuery) -4) );
					$query = $this->connection->PREPARE($buildQuery);
					for($i=0; $i < $numParams; $i++){
						$query->bindParam(":value_".$i, $values[$i]);
					}
					if( $query->execute() ){
						if( $asArray == true ){
							return $query->fetchAll(PDO::FETCH_ASSOC);
						}else{
							$objArray = array();
							while( $result = $query->fetchObject("formsavejson") ){
								$object = $result;
								$objArray[] = $object;
							}
							return $objArray;
						}
					}
				}
			}
		}

		/*get properties*/
		function getObjectsProperties(){
			$properties = array();
			foreach ($this as $key => $value) {
				if( $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
					$properties[] = $key;
				}
			}
			return $properties;
		}
		/*Human readable print out of object*/
		function printFormatted($return=false){
			if($return){
				return '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}else{
				echo '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}
		}

	}
?>