<?php
/*  Class Generated by Brendon Irwin's Class Generator

	Class: Formcode

	formID, i
	codeType, i
	version, i
	code, lt

*/

	class Formcode{
		private $id;
		private $connection;
		private $errors;
		private $errorCount;
		private $formID;
		private $codeType;
		private $version;
		private $code;


		/*Constructor*/
		function __construct($databaseConnection=null){
			$this->connection = $databaseConnection;
		}

		/*Getters and Setters*/
		function getId(){
			return $this->id;
		}

		function setId($id){
			$this->id = $id;
		}

		function getConnection(){
			return $this->connection;
		}

		function setConnection($connection){
			$this->connection = $connection;
		}

		function getErrors(){
			return $this->errors;
		}

		function setErrors($errors){
			$this->errors = $errors;
		}

		function getErrorCount(){
			return $this->errorCount;
		}

		function setErrorCount($errorCount){
			$this->errorCount = $errorCount;
		}

		function getFormID(){
			return $this->formID;
		}

		function setFormID($formID){
			$this->formID = $formID;
		}

		function getCodeType(){
			return $this->codeType;
		}

		function setCodeType($codeType){
			$this->codeType = $codeType;
		}

		function getVersion(){
			return $this->version;
		}

		function setVersion($version){
			$this->version = $version;
		}

		function getCode(){
			return $this->code;
		}

		function setCode($code){
			$this->code = $code;
		}

		/*Special Functions*/
		function load($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						$formcode = $query->fetchObject("formcode");
					}
					if( is_object( $formcode ) ){
						$formcode->setConnection( $this->connection );
					}
					return $formcode;
				}
			}
		}

		function getFromPost(){
			$this->setFormID( (isset($_POST["formID"])) ? $_POST["formID"] : $this->getFormID() );
			$this->setCodeType( (isset($_POST["codeType"])) ? $_POST["codeType"] : $this->getCodeType() );
			$this->setVersion( (isset($_POST["version"])) ? $_POST["version"] : $this->getVersion() );
			$this->setCode( (isset($_POST["code"])) ? $_POST["code"] : $this->getCode() );
		}

		function getFromRequest(){
			$this->setFormID( (isset($_REQUEST["formID"])) ? $_REQUEST["formID"] : $this->getFormID() );
			$this->setCodeType( (isset($_REQUEST["codeType"])) ? $_REQUEST["codeType"] : $this->getCodeType() );
			$this->setVersion( (isset($_REQUEST["version"])) ? $_REQUEST["version"] : $this->getVersion() );
			$this->setCode( (isset($_REQUEST["code"])) ? $_REQUEST["code"] : $this->getCode() );
		}

		function getFromArray($arr){
			$this->setFormID( (isset($arr["formID"])) ? $arr["formID"] : $this->getFormID() );
			$this->setCodeType( (isset($arr["codeType"])) ? $arr["codeType"] : $this->getCodeType() );
			$this->setVersion( (isset($arr["version"])) ? $arr["version"] : $this->getVersion() );
			$this->setCode( (isset($arr["code"])) ? $arr["code"] : $this->getCode() );
		}

		function compareTo($formcode){
			$log = array();
			if($this->getId() != $formcode->getId() ){
				$log["Id"] = "modified";
			}else{
				$log["Id"] = "un-modified";
			}
			if($this->getConnection() != $formcode->getConnection() ){
				$log["Connection"] = "modified";
			}else{
				$log["Connection"] = "un-modified";
			}
			if($this->getErrors() != $formcode->getErrors() ){
				$log["Errors"] = "modified";
			}else{
				$log["Errors"] = "un-modified";
			}
			if($this->getErrorCount() != $formcode->getErrorCount() ){
				$log["ErrorCount"] = "modified";
			}else{
				$log["ErrorCount"] = "un-modified";
			}
			if($this->getFormID() != $formcode->getFormID() ){
				$log["FormID"] = "modified";
			}else{
				$log["FormID"] = "un-modified";
			}
			if($this->getCodeType() != $formcode->getCodeType() ){
				$log["CodeType"] = "modified";
			}else{
				$log["CodeType"] = "un-modified";
			}
			if($this->getVersion() != $formcode->getVersion() ){
				$log["Version"] = "modified";
			}else{
				$log["Version"] = "un-modified";
			}
			if($this->getCode() != $formcode->getCode() ){
				$log["Code"] = "modified";
			}else{
				$log["Code"] = "un-modified";
			}
		return $log;
		}

		function save(){
			$id = $this->getId();
			$formID = $this->getFormID();
			$codeType = $this->getCodeType();
			$version = $this->getVersion();
			$code = $this->getCode();
			if( $this->connection ){
				if( $id != "" ){
					/*Perform Update Operation*/
					$query = $this->connection->prepare("UPDATE  `formcode` SET `formID` = :formID ,`codeType` = :codeType ,`version` = :version ,`code` = :code WHERE `id` = :id");
					$query->bindParam('formID', $formID);
					$query->bindParam('codeType', $codeType);
					$query->bindParam('version', $version);
					$query->bindParam('code', $code);
					$query->bindParam('id', $id);
					if( $query->execute() ){
						return $id;
					}else{
						return -1;
					}

				}else{
					/*Perform Insert Operation*/
					$query = $this->connection->prepare("INSERT INTO `formcode` (`id`,`formID`,`codeType`,`version`,`code`) VALUES (NULL,:formID,:codeType,:version,:code);");
					$query->bindParam(':formID', $formID);
					$query->bindParam(':codeType', $codeType);
					$query->bindParam(':version', $version);
					$query->bindParam(':code', $code);

					if( $query->execute() ){
						$this->setId( $this->connection->lastInsertId() );
						return $this->getId();
					}else{
						return -1;
					}	
				}
			}
		}


		function delete($id = null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				if( $id != "" ){
					$query = $this->connection->prepare("DELETE FROM `formcode` WHERE `id` = :id");
					$query->bindParam(':id', $id);
					if( $query->execute() ){
						return 1;
					}else{
						return 0;
					}
				}
			}
		}

		function getById($id){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `id` = :id LIMIT 1");
				$query->bindParam(':id', $id);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByFormID($formID){
			if( $this->connection ){
				if( $formID == null && $this->getFormID() != ""){
					$formID = $this->getFormID();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `formID` = :formID LIMIT 1");
				$query->bindParam(':formID', $formID);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByCodeType($codeType){
			if( $this->connection ){
				if( $codeType == null && $this->getCodeType() != ""){
					$codeType = $this->getCodeType();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `codeType` = :codeType LIMIT 1");
				$query->bindParam(':codeType', $codeType);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByVersion($version){
			if( $this->connection ){
				if( $version == null && $this->getVersion() != ""){
					$version = $this->getVersion();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `version` = :version LIMIT 1");
				$query->bindParam(':version', $version);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}

		function getByCode($code){
			if( $this->connection ){
				if( $code == null && $this->getCode() != ""){
					$code = $this->getCode();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `code` = :code LIMIT 1");
				$query->bindParam(':code', $code);
				$object = null;

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$object = $result;
					}

				}
				if( is_object( $object ) ){
					return $object;
				}
			}
		}


		function getListById($id=null){
			if( $this->connection ){
				if( $id == null && $this->getId() != ""){
					$id = $this->getId();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `id` = :id");
				$query->bindParam(':id', $id);

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$formcodes[] = $result;
					}
					if( is_array( $formcodes ) ){
						return $formcodes;
					}else{
						return array();
					}

				}
			}
		}

		function getListByFormID($formID=null){
			if( $this->connection ){
				if( $formID == null && $this->getFormID() != ""){
					$formID = $this->getFormID();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `formID` = :formID");
				$query->bindParam(':formID', $formID);

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$formcodes[] = $result;
					}
					if( is_array( $formcodes ) ){
						return $formcodes;
					}else{
						return array();
					}

				}
			}
		}

		function getListByCodeType($codeType=null){
			if( $this->connection ){
				if( $codeType == null && $this->getCodeType() != ""){
					$codeType = $this->getCodeType();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `codeType` = :codeType");
				$query->bindParam(':codeType', $codeType);

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$formcodes[] = $result;
					}
					if( is_array( $formcodes ) ){
						return $formcodes;
					}else{
						return array();
					}

				}
			}
		}

		function getListByVersion($version=null){
			if( $this->connection ){
				if( $version == null && $this->getVersion() != ""){
					$version = $this->getVersion();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `version` = :version");
				$query->bindParam(':version', $version);

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$formcodes[] = $result;
					}
					if( is_array( $formcodes ) ){
						return $formcodes;
					}else{
						return array();
					}

				}
			}
		}

		function getListByCode($code=null){
			if( $this->connection ){
				if( $code == null && $this->getCode() != ""){
					$code = $this->getCode();
				}

				/*Perform Query*/
				$query = $this->connection->prepare("SELECT * FROM `formcode` WHERE `code` = :code");
				$query->bindParam(':code', $code);

				if( $query->execute() ){
					while( $result = $query->fetchObject("formcode") ){
						$formcodes[] = $result;
					}
					if( is_array( $formcodes ) ){
						return $formcodes;
					}else{
						return array();
					}

				}
			}
		}

		/*Return parameter (object) as Array*/
		function toArray ($obj=null) {
			if (is_object($obj)) $obj = (array)$obj;
			if (is_array($obj)) {
				$new = array();
				foreach ($obj as $key => $val) {
					$class = get_class($this);
					$k = $key;
					$fkey = trim( str_replace( $class,"",$k));
					if( $fkey == "connection" || $fkey == "errors" || $fkey == "errorCount" ){
						//dont add
					}else{
						$new[$fkey] = $this->toArray($val);
					}
				}
			} else {
				$new = $obj;
			}
			return $new;
		}

		/*Return object as Array*/
		function asArray(){
			$array = $this->toArray( $this );
			return $array;
		}

		/*Return object as JSON String*/
		function asJSON(){
			return json_encode($this->asArray());
		}

		/*Return clone of Object*/
		function getClone(){
			return clone($this);
		}


		/*Echo array as CSV file*/
		function arrayToCSVFile($array, $filename="formcode.csv", $delimiter=",", $showHeader=true){
			ob_clean();
			if( !is_array($array) ){
				$array = $this->asArray();
			}
			if( !is_array($showHeader) && $showHeader == true){
				$header=array();
				foreach( $array[0] as $key => $value){
					$header[] = strtoupper($key);
				}
				array_unshift($array, $header);
			}
			if( is_array($showHeader) ){
				array_unshift($array, $showHeader);
			}
			header('Content-Type: application/csv; charset=UTF-8');
			header('Content-Disposition: attachement; filename="'.$filename.'";');
			$f = fopen('php://output', 'w');
			foreach ($array as $line) {
				fputcsv($f, $line, $delimiter);
			}
			exit;
		}


		/*getObjectsLikeThis - returns array*/
		function getObjectsLikeThis($asArray=true){
			if( $this->connection ){
				$buildQuery="SELECT * FROM `formcode` WHERE ";
				$numParams = 0;
				$values = array();
				foreach ($this as $key => $value) {
					if( $value != "" && $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
						$buildQuery.="`".$key."` = :value_".$numParams." AND ";
						$numParams++;
						$values[] = $value;
					}
				}
				if( $numParams > 0 ){
					//remove last AND
					$buildQuery = substr( $buildQuery , 0, (strlen($buildQuery) -4) );
					$query = $this->connection->PREPARE($buildQuery);
					for($i=0; $i < $numParams; $i++){
						$query->bindParam(":value_".$i, $values[$i]);
					}
					if( $query->execute() ){
						if( $asArray == true ){
							return $query->fetchAll(PDO::FETCH_ASSOC);
						}else{
							$objArray = array();
							while( $result = $query->fetchObject("formcode") ){
								$object = $result;
								$objArray[] = $object;
							}
							return $objArray;
						}
					}
				}
			}
		}

		/*get properties*/
		function getObjectsProperties(){
			$properties = array();
			foreach ($this as $key => $value) {
				if( $key != "id" && $key != "connection" && $key != "error" && $key != "errorCount"){
					$properties[] = $key;
				}
			}
			return $properties;
		}
		/*Human readable print out of object*/
		function printFormatted($return=false){
			if($return){
				return '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}else{
				echo '<pre>'.print_r( $this->asArray(), true ).'</pre>';
			}
		}

	}
?>