<?php
	include "../../includes/include.php";
	pageHeader();
?>
<!--Form Generated by Brendon Irwin's Form Generator-->
<?php
	$conn = getConnection(); //set to DB Conn
	$theform = new Theform($conn); 
	if(strtoupper($_SERVER["REQUEST_METHOD"]) === "POST") {
		$theform->getFromPost();
		$theform->setEnabled(1);
		$theform->setCreated( time() );
		
		$theform->save();
		
		echo $theform->printFormatted();
	}
?>

<style type="text/css">
.formRow{
	clear: both;
	width: 780px;
	padding: 10px 10px;
	margin: 0 auto;
}
.rowLabel{ float: left; width: 49%; clear: left; }
.rowField{ float: right; width: 49%; clear: right; }
.rowCenter{ width: 100%; clear: both; text-align: center; }

.rowCenter input[type="submit"],
.rowCenter input[type="reset"]{
	margin: 0px 10px; cursor: pointer;
}

input.login:valid,
input.empty:valid{
	box-shadow: none;
	background-image: none;
	border: 1px solid #000;
}

select:required,
select:invalid,
input:invalid,
input:required {
	box-shadow: 3px 1px 5px rgba(200, 0, 0, 0.85);
	border: 1px solid rgb(200,0,0);
}

select:valid{
	box-shadow: none;
	border: 1px solid #000;
}

input:valid{
	box-shadow: none;
	background-image: url('images/correct.png');
	background-position: 95%;
	background-repeat: no-repeat;
	border: 1px solid #0f0;
}

textarea{
	min-height: 100px;
}

.button{
	cursor: pointer;
	-moz-box-shadow:inset 0px 1px 0px 0px #97c4fe;
	-webkit-box-shadow:inset 0px 1px 0px 0px #97c4fe;
	box-shadow:inset 0px 1px 0px 0px #97c4fe;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #3d94f6), color-stop(1, #1e62d0) );
	background:-moz-linear-gradient( center top, #3d94f6 5%, #1e62d0 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#3d94f6', endColorstr='#1e62d0');
	background-color:#3d94f6;
	border: 1px solid #3d94f6!important;
	-webkit-border-top-left-radius:4px;
	-moz-border-radius-topleft:4px;
	border-top-left-radius:4px;
	-webkit-border-top-right-radius:4px;
	-moz-border-radius-topright:4px;
	border-top-right-radius:4px;
	-webkit-border-bottom-right-radius:4px;
	-moz-border-radius-bottomright:4px;
	border-bottom-right-radius:4px;
	-webkit-border-bottom-left-radius:4px;
	-moz-border-radius-bottomleft:4px;
	border-bottom-left-radius:4px;
	text-indent:0;
	border:1px solid #337fed;
	display:inline-block;
	color:#ffffff;
	font-family:Arial;
	font-size:13px;
	font-weight:normal;
	font-style:normal;
	height:auto;
	line-height:22px;
	width:auto;
	text-decoration:none;
	text-align:center;
	text-shadow:1px 1px 0px #1570cd;
	padding: 5px 20px;
}

.button:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #1e62d0), color-stop(1, #3d94f6) );
	background:-moz-linear-gradient( center top, #1e62d0 5%, #3d94f6 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#1e62d0', endColorstr='#3d94f6');
	background-color:#1e62d0;
}

.button:active {
	position:relative;
	top:1px;
}

.item_restrict_dates{
	width: 100%;

}

</style>
<script>
$(function(){
	$('#sunrise,#sunset').datepicker( {"dateFormat" : "mm/dd/yy"});
});
</script>


<form name="theform" id="theform" method="POST" action="" enctype="multipart/form-data">
	<div class="formRow">
		<div class="rowLabel">
			<label for="title">Title:*</label>
		</div>
		<div class="rowField">
			<input type="text" name="title" id="title" value="<?php echo (isset($theform) ?  $theform->getTitle() : ''); ?>"  title="Title required" required="required"/>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="description">Description of Form:</label>
		</div>
		<div class="rowField">
			<textarea name="description" id="Description"  title="" ><?php echo (isset($theform) ?  $theform->getDescription() : ''); ?></textarea>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="encryptionMode">Encryption Mode::*</label>
		</div>
		<div class="rowField">
			<?php $encryptionMode_values = array("All", " Some", " None"); ?>
			<?php for($sm = 0; $sm < sizeof( $encryptionMode_values); $sm++){ ?>
				<label><?php echo $encryptionMode_values[$sm]; ?>: <input type="radio" name="encryptionMode" id="encryptionMode" value="<?php echo $sm; ?>" <?php if( ( is_object($theform) &&  $theform->getEncryptionMode() ?  $theform->getEncryptionMode()  : '') == $sm){ echo " checked"; } ?>  required="required" /></label><br />
			<?php } ?>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="encryptionSalt">Encryption Salt:</label>
		</div>
		<div class="rowField">
			<input type="text" name="encryptionSalt" id="encryptionSalt" value="<?php echo (isset($theform) ?  $theform->getEncryptionSalt() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="owner">Owner:</label>
		</div>
		<div class="rowField">
			<input type="number" name="owner" id="owner" value="<?php echo (isset($theform) ?  $theform->getOwner() : ''); ?>" title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="jqVersion">Jquery Version:</label>
		</div>
		<div class="rowField">
			<input type="text" name="jqVersion" id="jqVersion" value="<?php echo (isset($theform) ?  $theform->getJqVersion() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="jqTheme">jQuery Theme:</label>
		</div>
		<div class="rowField">
			<input type="text" name="jqTheme" id="jqTheme" value="<?php echo (isset($theform) ?  $theform->getJqTheme() : ''); ?>"  title="" />
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="sunrise">Sun rise::</label>
		</div>
		<div class="rowField">
			<label>(mm/dd/yyyy) <input class="dateInput" type="text" name="sunrise" id="sunrise" value="<?php echo (isset($theform) ?  $theform->getSunrise() : ''); ?>" title=" Date should be in format mm/dd/yyyy"/></label>
		</div>
	</div>
	<div class="formRow">
		<div class="rowLabel">
			<label for="sunset">Sun set::</label>
		</div>
		<div class="rowField">
			<label>(mm/dd/yyyy) <input class="dateInput" type="text" name="sunset" id="sunset" value="<?php echo (isset($theform) ?  $theform->getSunset() : ''); ?>" title=" Date should be in format mm/dd/yyyy" /></label>
		</div>
	</div>
	<div class="formRow rowCenter">
		<input class="button" type="submit" value="SUBMIT" />
	</div>
</form>
<?php
	pageFooter();
?>